# Generated by Django 3.2.7 on 2021-10-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20211005_1755'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='seen_movies',
        ),
        migrations.RemoveField(
            model_name='user',
            name='want_to_see_movies',
        ),
        migrations.AddField(
            model_name='user',
            name='watched_movies',
            field=models.ManyToManyField(related_name='watched_movies', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(related_name='watchlist', to='movies.Movie'),
        ),
    ]
