# Generated by Django 3.2.8 on 2021-10-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_user_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default_movie.png', upload_to='assets/user_images'),
        ),
    ]
