# Generated by Django 3.2.8 on 2021-10-18 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
