# Generated by Django 3.2.7 on 2021-10-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.IntegerField()),
                ('biography', models.TextField(blank=True, null=True)),
                ('birthday', models.DateField()),
                ('movies', models.ManyToManyField(to='movies.Movie')),
            ],
        ),
    ]
