# Generated by Django 3.2.8 on 2021-10-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='image',
            field=models.ImageField(default='assets/default_movie.png', upload_to='actors'),
        ),
    ]
