# Generated by Django 3.2.8 on 2021-10-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_actor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.ImageField(default='/home/isaac_develops/kenzie/q4/imdb-app/assets/default_movie.png', upload_to='actors'),
        ),
    ]
