# Generated by Django 3.2.8 on 2021-10-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0004_alter_actor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.ImageField(default='static/images/default_movie.png', upload_to='assets'),
        ),
    ]
