# Generated by Django 3.2.7 on 2021-10-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='release_date',
            new_name='year_of_production',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='overview',
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('A', 'Action'), ('D', 'Drama'), ('C', 'Comedy'), ('R', 'Romance')], default='AC', max_length=1),
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='assets/default_movie.png', upload_to='movies'),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('GR', 'German'), ('FR', 'French')], default='EN', max_length=2),
        ),
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('RA', 'Recently Added'), ('MW', 'Most Watched'), ('TR', 'Top Rated')], default='RA', max_length=2),
        ),
        migrations.AddField(
            model_name='movie',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
