# Generated by Django 3.2.6 on 2021-10-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20211005_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('imageurl', models.CharField(max_length=1000)),
                ('targetUrl', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('imageurl', models.CharField(max_length=1000)),
                ('targetUrl', models.CharField(max_length=1000)),
            ],
        ),
    ]
